tap "derailed/k9s"
tap "homebrew/bundle"
tap "homebrew/core"
brew "bazelisk"
brew "fzf"
brew "git"
brew "go@1.19", link: true
brew "jq"
brew "neovim"
brew "node"
brew "nvm"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "stow"
brew "yarn"
brew "zsh-syntax-highlighting"
brew "derailed/k9s/k9s"
