# Unfortunately, this file does not allow pinning of versions for every
# package. Thus, some have versions and some do not.
tap "homebrew/bundle"
tap "homebrew/core"
brew "awscli"
brew "bazelisk"
brew "fzf"
brew "git"
brew "go@1.19", link: true
brew "grep"
brew "gnupg"
brew "hashicorp/tap/terraform-ls"
brew "helm"
brew "helmfile"
brew "jq"
brew "k9s"
brew "maven@3.8"
brew "neovim"
brew "netcat"
brew "nmap"
brew "nvm"
brew "openjdk@18"
brew "pipx"
brew "pre-commit"
brew "pyenv"
brew "pyenv-virtualenv"
brew "ripgrep"
brew "stow"
brew "tfenv"
brew "tmux"
brew "telnet"
brew "yarn"
brew "vault"
brew "zsh-syntax-highlighting"
