#!/bin/bash

# CORE
# Ensure all shells only allow 256 color
export TERM=screen-256color
export VISUAL=nvim
export EDITOR="$VISUAL"
# Append last command to history before returning prompt. This will save bash
# history even if multiple bash sessions are in use.
export PROMPT_COMMAND='history -a'
# Add custom binaries to path
export PATH="$HOME/.local/bin:$PATH"

### FZF
# Install fzf triggers
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

### GPG
# For signing git commits.
export GPG_TTY=$(tty)

### GIT
export PATH="$HOME/.git-commands:$PATH"

alias gpoht='git push origin HEAD && git push origin --tags'
alias gt='git tag'
alias gdmh='git diff master HEAD'
alias git-flush='git add . && git reset HEAD --hard'

function gupm() {
	branch=$(git branch --show-current)
	if [ "$branch" = "main" ] || [ "$branch" = "master" ]; then
		git fetch upstream
		git pull upstream $branch
		git push origin $branch
		git fetch
	else
		echo "Can not gupm while on $branch"
	fi
}


git-help() {
  echo "gt — git tag"
  echo "gdct — git describe --tags 'git rev-list --tags --max-count=1'"
  echo "gpoat — git push origin --all && git push origin --tags"
  echo "gpoht — git push origin HEAD && git push origin tag"
  echo "gdtag - git tag --delete <tag> && git push origin :refs/tags/<tag>"
  echo "gdmh - git diff master HEAD"
  echo "gupm - git fetch upstream && git pull upstream master && git push origin master"
}

### PyEnv
export PYENV_VIRTUALENV_DISABLE_PROMPT=0
# Add pyenv to path
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
# Add pyenv autocompletion
eval "$(pyenv init -)"
# Add pyenv virtualenv autocompletion to path
# This can really slow down CLI prompt
# eval "$(pyenv virtualenv-init -)"

### pipx
# First install pipx. Then install argcomplete
# to get arg completion.
if command -v register-python-argcomplete &> /dev/null
then
	eval "$(register-python-argcomplete pipx)"
fi


### Golang
export GOPATH="$HOME/Code/go"
export PATH="$GOPATH/bin:$PATH"

### gcloud
# The next line updates PATH for the Google Cloud SDK.
if [ -f "$HOME/Code/google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/Code/google-cloud-sdk/path.zsh.inc"; fi
# The next line enables shell command completion for gcloud.
if [ -f "$HOME/Code/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/Code/google-cloud-sdk/completion.zsh.inc"; fi

### Node/JS
export NVM_DIR="$HOME/.nvm"
[ -s "$HOMEBREW_PREFIX/opt/nvm/nvm.sh" ] && \. "$HOMEBREW_PREFIX/opt/nvm/nvm.sh"  # This loads nvm
[ -s "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm" ] && \. "$HOMEBREW_PREFIX/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

### Tmux
# if [ ! -f '/usr/local/bin/tmux' ]; then
#   ln -s "$HOME/Code/tmux/tmux" /usr/local/bin/tmux
# fi

tmux-help() {
  echo "Rename pane: select-pane -t 1 -T 'Test'"
  echo "Show pane names: set pane-border-status"
}
